import Head from 'next/head';
//import styles from '@/styles/Home.module.css';
import styles from '../components/login.module.css';
import { signIn } from 'next-auth/react';
import Image from 'next/image';


export default function Home() {

  return (
    <>
      <Head>
        <title>Abac Scholarship Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles['login-page']}>
        <div className={styles['login-container']}>
          <Image src="/abac_logo.png" alt="Image" width={90} height={90} className={styles['logo-image']}/>
          <h2 className={styles['custom-h2']}>Abac Scholarship </h2>
          <div className={styles['buttons-container']}>
            <button
              className={styles['loginbutton']}
              onClick={() => {
                signIn(
                  'azure-ad',
                  { callbackUrl: '/studentHome' },
                  { prompt: 'login' },
                );
              }}
            >
              Log in
            </button>
          </div>
        </div>
      </main>
    </>
  );
}